services:
  easydb:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: easydb
    restart: unless-stopped
    environment:
      PORT: ${PORT:-3000}
    ports:
      - "80:80"
    volumes:
      - ./logs:/app/logs
      - ./runtime:/app/runtime
